sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Hjw1829669
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tBVV4MYmzFFDzvT5NKU
    access-key-secret: YHUPVBvdJk9Egr2GoM0sj8dk0XPsL9
    bucket-name: sky-take-out-ttk
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
